### ISSUE TITLE
Example in readme.md does not work

### ISSUE THREAD

**Issue by at0g** [ediket/nothinkdb#10]
When running the example in the readme as-is, I see the following error:

```
ValidationError: {
  "table": "user",
  "tableName" [1]: -- missing --
}

```

ok... after changing `table` to `tableName`, the error disappears but nothing else happens (I'm expecting to see the newly created users in the console).

The [example from rethinkdb](https://www.rethinkdb.com/docs/install-drivers/javascript) works fine.

**Comment by ironhee** [comment]
fixed by https://github.com/ediket/nothinkdb/pull/11 :D Thank you
